greetings = [
    'Hallo',
    'Përshëndetje',
    'እው ሰላም ነው',
    'مرحبًا',
    'Barev',
    'Kamisaki',
    'Salam',
    'Kaixo',
    'Вітаю',
    'হ্যালো',
    'Zdravo',
    'Здравейте',
    'ဟယ်လို',
    '你好',
    'Hola',
    'Kamusta',
    'Moni',
    'Bonghjornu',
    'Zdravo',
    'Ahoj',
    'Hej',
    'Hallo',
    'Hello',
    'Tere',
    'Hello',
    'سلام',
    'Bula',
    'Kumusta',
    'Hei',
    'Bonjour',
    'Dia dhuit',
    'Ola',
    'გამარჯობა',
    'Guten tag',
    'γεια',
    'Mba\'éichapa',
    'Bonjou',
    'Aloha',
    'שלום',
    'नमस्ते',
    'Nyob zoo',
    'Szia',
    'Halló',
    'Ndewo',
    'Hello',
    'Halo',
    'Ciao',
    'こんにちは',
    'Сәлеметсіз бе',
    'សួស្តី',
    'Mwaramutse',
    '안녕하세요',
    'Slav',
    'ສະບາຍດີ',
    'Salve',
    'Sveika',
    'Sveiki',
    'Moien',
    'Salama',
    'Selamat pagi',
    'Bongu',
    '你好',
    'Kia ora',
    'नमस्कार',
    'сайн уу',
    'Niltze Tialli Pialli',
    'Ya’at’eeh',
    'नमस्कार',
    'Hei',
    'سلام',
    'Cześć',
    'Olá',
    'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    'Akkam',
    'Allianchu',
    'Bunâ',
    'Привет',
    'Talofa',
    'Thobela',
    'Zdravo',
    'Dumela',
    'Ahoj',
    'Zdravo',
    'Hello',
    'Hola',
    'Jambo',
    'Hallå',
    'Kamusta',
    'Ia Orana',
    'Li-hó',
    'வணக்கம்',
    'สวัสดี',
    'Tashi delek',
    'Mālō e lelei',
    'Avuxeni',
    'Merhaba',
    'привіт',
    'السلام عليكم'
]

import random
number = random.randint(0,len(greetings)-1)
print (f'{greetings[number]} (it means hello)')
